name: Ionic GitHub CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run ci:test

  e2e:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run ci:cy-run
          build: npm run ng run app:build:production
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{github.token}}
